### ISSUE TITLE
[UPDATE] Vars repository

### ISSUE THREAD

**Issue by DerekTBrown** [retr0h/ansible-etcd#17]
I am using this repository with some non-standard OSes (CoreOS, Alpine) which have directories that differ from the defaults.  I realize this is something that lots of users probably have to configure themselves.  I thought it might be a good idea to create some pre-defined configurations in the var directory, for example var/coreos.yml so that people could just include these when writing their code.  Is this something you are interested in?

**Comment by retr0h** [comment]
Hi @DerekTBrown.  I am always interested in making it better.  Are the directories standard directories for CoreOS and Alpine?  If so, I woudn't mind we update the role to use those dirs based on the os family.

**Comment by DerekTBrown** [comment]
Yes- they are standard directories, and that is exactly what I was thinking.

**Comment by DerekTBrown** [comment]
One design decision we need to make- CoreOS requires using a bootstrap to enable Python (https://github.com/defunctzombie/ansible-coreos-bootstrap), do we include this in the role, or assume people have already figured this out?

**Comment by retr0h** [comment]
Probably assume they have done that already, unless others care...  Maybe we should document that in the README under Dependencies?

**Comment by DerekTBrown** [comment]
Perfect! Working on a fork:

https://github.com/retr0h/ansible-etcd/pull/18
