### ISSUE TITLE
Error on upstart script installation step

### ISSUE THREAD

**Issue by mflopez79** [retr0h/ansible-etcd#20]
Hello! I received the following error when running your role againts Ubuntu 14.04 boxes (ansible 2.1)

```bash
TASK [etcd : Add etcd upstart service] *****************************************
fatal: [172_XXX_XXX_XXX]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/etc/init/etcd.conf", "mode": "0644", "src": "etc/init/etcd.conf.j2"}, "module_name": "template"}, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'etcd'"}
fatal: [172_XXX_XXX_XXX]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/etc/init/etcd.conf", "mode": "0644", "src": "etc/init/etcd.conf.j2"}, "module_name": "template"}, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'etcd'"}
```

The only variable I overwrote was `etcd_interface`, rest is in default values.
Could you please take a look at it? I'm not seeing where the error is

Thanks!

**Comment by retr0h** [comment]
Still having this problem?

**Comment by mflopez79** [comment]
Yes

**Comment by retr0h** [comment]
> Yes

Not sure what the problem is.  If you look at the tests, we are currently converging 14.04, 16.04, and centos 7 w/o issue.

**Comment by retr0h** [comment]
@mflopez79 The role by default assume you are deploying to a group named `etcd`.  If you do not have that group defined you will need to define `etcd_peers_group` appropriately.

**Comment by retr0h** [comment]
Reopen if still having issues.
