### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by waddles** [retr0h/ansible-etcd#34]
Fantastic work, thanks very much.

I get a deprecation warning on hosts in my playbook that are not in the etcd peers group.
```
TASK [retr0h.etcd : Install system dependencies for synchronize] ***************
task path: /Users/fitzpatw/projects/ansible/roles/retr0h.etcd/tasks/main.yml:8
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'etcd_install_dependencies' is undefined.
This feature will be removed in
a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [human] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```

Also systemd does not correctly restart services when the unit file changes, as it needs a `systemctl daemon-reload` in order to recognise the new unit file. It was easily fixed with another handler though.

**Comment by retr0h** [comment]
Hey @waddles.  I'll check it out.  Thanks for the report.  BTW, what distro are you running?
