### ISSUE TITLE
Is release v5.0 a mistake or is it for real?

### ISSUE THREAD

**Issue by dhensen** [retr0h/ansible-etcd#42]
Hello John,

I was doing some research on which etcd ansible role I am going to use. I then noticed this repo and another that is a good candidate. However in your [releases](https://github.com/retr0h/ansible-etcd/releases) and on [ansible-galaxy](https://galaxy.ansible.com/retr0h/etcd/) I see a 5.0 version that doesn't make any sense, because that 5.0 is released from a gilt branch containing an empty file.

Can you enlighten me/us about this situation? When looking at your role it looks most promising compared to others, but this release thing holds me back.

Regards,

Dino

**Comment by retr0h** [comment]
Hi @dhensen that was a test and not at all related to the project.  I can delete it if it helps 👍

**Comment by dhensen** [comment]
Ok, deleting it would be good for me and others as well. I think because of this more people are going for the other etcd roles now. But I could not figure out why, because yours is more complete and the only role that is tested (at least it has a build status). So maybe that's it.. 

Thanks for the quick reply

**Comment by retr0h** [comment]
> is tested (at least it has a build status). So maybe that's it..

Yeah, the roll is fully tested with [Molecule](http://molecule.readthedocs.io/en/stable-1.20/).

**Comment by retr0h** [comment]
I removed the invalid 5.0 tag from git, however, I don't believe that can be removed from ansible-galaxy.  Personally, I'd recommend not using `ansible-galaxy`, and pinning deps from git using a tool such as [Gilt](http://gilt.readthedocs.io/en/stable-1.0/).

**Comment by dhensen** [comment]
Thanks for the tip! I didn't know Gilt yet, it looks something I need for other git projects too. Where I have 10+ submodules that are spinning out of control!

**Comment by retr0h** [comment]
You good if I close this?

**Comment by dhensen** [comment]
Yep, I'm good. Thanks for your help
